// Pure constants — no server imports. Safe to use in both server and client components.

export const TEMPLATE_TYPES = [
  "welcome",
  "trial_day7",
  "trial_day12",
  "trial_reminder_3d",
  "trial_expired",
  "reengagement_7",
  "reengagement_14",
  "reengagement_21",
  "data_warning",
  "data_wiped",
  "churn_reason",
  "churn_thanks",    // sent after churn reason button click
  "nps",
  "nps_followup",   // sent to NPS detractors (score 0-6) within hours
] as const;

export type TemplateType = (typeof TEMPLATE_TYPES)[number];

export const TEMPLATE_LABELS: Record<TemplateType, string> = {
  welcome:           "Welcome (after email verification)",
  trial_day7:        "Day 7 check-in (7 days into trial)",
  trial_day12:       "Day 12 urgency (2 days left on trial)",
  trial_reminder_3d: "3-day reminder (trial ending soon)",
  trial_expired:     "Trial expired (sent same day)",
  reengagement_7:    "Day 7 post-expiry re-engagement",
  reengagement_14:   "Day 14 post-expiry",
  reengagement_21:   "Day 21 post-expiry (last chance — data removal date shown)",
  data_warning:      "Day 30: data deleted within 24 hours (date shown)",
  data_wiped:        "Day 31: data has been removed",
  churn_reason:      "Churn survey (2-3 days post-expiry)",
  churn_thanks:      "Churn thank-you (sent after reason button click)",
  nps:               "NPS survey (day 10 of trial)",
  nps_followup:      "NPS follow-up (sent to detractors: score 0-6)",
};

// {{reasonButtons}} and {{scoreButtons}} are special — generated by the cron at send time.
// Do NOT remove these placeholders when editing churn_reason or nps templates.
export const TEMPLATE_VARS: Record<TemplateType, string[]> = {
  welcome:           ["{{name}}", "{{dashboardUrl}}", "{{trialEndsAt}}"],
  trial_day7:        ["{{name}}", "{{dashboardUrl}}"],
  trial_day12:       ["{{name}}", "{{upgradeUrl}}", "{{trialEndsAt}}", "{{price}}"],
  trial_reminder_3d: ["{{name}}", "{{trialEndsAt}}", "{{upgradeUrl}}", "{{price}}", "{{annualFreeMonths}}"],
  trial_expired:     ["{{name}}", "{{upgradeUrl}}", "{{price}}"],
  reengagement_7:    ["{{name}}", "{{upgradeUrl}}", "{{price}}"],
  reengagement_14:   ["{{name}}", "{{upgradeUrl}}", "{{price}}"],
  reengagement_21:   ["{{name}}", "{{upgradeUrl}}", "{{deletionDate}}"],
  data_warning:      ["{{name}}", "{{upgradeUrl}}", "{{deletionDate}}"],
  data_wiped:        ["{{name}}", "{{baseUrl}}"],
  churn_reason:      ["{{name}}", "{{reasonButtons}}", "{{feedbackUrl}}"],
  churn_thanks:      ["{{name}}", "{{upgradeUrl}}"],
  nps:               ["{{name}}", "{{scoreButtons}}"],
  nps_followup:      ["{{name}}", "{{score}}"],
};

export const DEFAULT_SUBJECTS: Record<TemplateType, string> = {
  welcome:           "Welcome to Estimate Nepal: here's how to get started",
  trial_day7:        "How's your Estimate Nepal trial going?",
  trial_day12:       "2 days left on your Estimate Nepal trial",
  trial_reminder_3d: "Your Estimate Nepal trial ends in 3 days",
  trial_expired:     "Your Estimate Nepal trial has ended. Upgrade to continue.",
  reengagement_7:    "Your Estimate Nepal projects are still here",
  reengagement_14:   "Two weeks. Your data is still safe.",
  reengagement_21:   "Last chance: your Estimate Nepal data will be removed on {{deletionDate}}",
  data_warning:      "Your Estimate Nepal data will be deleted on {{deletionDate}}",
  data_wiped:        "Your Estimate Nepal trial data has been removed",
  churn_reason:      "Why did you stop? (takes 1 click)",
  churn_thanks:      "Thank you for telling us",
  nps:               "Quick question: how's Estimate Nepal working for you?",
  nps_followup:      "You gave us a {{score}} — can you tell us more?",
};

export const DEFAULT_BODIES: Record<TemplateType, string> = {
  welcome: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Welcome to Estimate Nepal!</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 8px">
      Your email is verified and your 14-day free trial has started.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:0 0 20px">
      <tr><td style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:12px 16px">
        <p style="color:#1e40af;font-size:14px;font-weight:600;margin:0">Trial expires: {{trialEndsAt}}</p>
      </td></tr>
    </table>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 20px">Here&apos;s how to get the most out of it:</p>
    <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px">
      <tr><td style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:16px 20px">
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr><td style="padding:8px 0;border-bottom:1px solid #dbeafe">
            <span style="color:#1d4ed8;font-weight:700;font-size:15px">1.</span>
            <span style="color:#1e40af;font-size:14px;padding-left:8px">Create your first project</span>
          </td></tr>
          <tr><td style="padding:8px 0;border-bottom:1px solid #dbeafe">
            <span style="color:#1d4ed8;font-weight:700;font-size:15px">2.</span>
            <span style="color:#1e40af;font-size:14px;padding-left:8px">Upload a drawing and set the scale</span>
          </td></tr>
          <tr><td style="padding:8px 0">
            <span style="color:#1d4ed8;font-weight:700;font-size:15px">3.</span>
            <span style="color:#1e40af;font-size:14px;padding-left:8px">Measure quantities and export your BOQ</span>
          </td></tr>
        </table>
      </td></tr>
    </table>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Need help getting started? Reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#1d4ed8;text-decoration:none">hello@estimatenepal.com</a>.
      We usually respond within a few hours.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{dashboardUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Go to Dashboard &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      You have <strong>14 days</strong> to explore everything for free. No credit card required.
    </p>`,

  trial_day7: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">How&apos;s your first week going?</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      You&apos;re 7 days into your Estimate Nepal trial. Have you had a chance to explore everything yet?
    </p>
    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#475569;font-size:14px;font-weight:600;margin:0 0 10px">Quick wins to try before your trial ends:</p>
      <ul style="color:#475569;font-size:14px;margin:0;padding-left:20px;line-height:2">
        <li>Upload a drawing and run a takeoff measurement</li>
        <li>Generate a BOQ from your takeoff data</li>
        <li>Export a PDF tender document</li>
        <li>Invite a team member to collaborate</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Need help getting set up? Reply to this email or reach us at
      <a href="mailto:hello@estimatenepal.com" style="color:#1d4ed8;text-decoration:none">hello@estimatenepal.com</a>.
      We usually respond within a few hours.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{dashboardUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Continue in Dashboard &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      You have 7 days remaining on your free trial.
    </p>`,

  trial_day12: `
    <h2 style="color:#dc2626;font-size:22px;font-weight:700;margin:0 0 8px">2 days left on your trial</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your Estimate Nepal trial expires on <strong>{{trialEndsAt}}</strong>. After that, you won&apos;t be able to create new exports, upload drawings, or edit projects.
    </p>
    <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#991b1b;font-size:14px;font-weight:600;margin:0 0 8px">Don&apos;t lose your work:</p>
      <ul style="color:#7f1d1d;font-size:14px;margin:0;padding-left:20px;line-height:1.8">
        <li>All drawings and measurements preserved</li>
        <li>BOQs and rate analyses kept</li>
        <li>Project history maintained</li>
        <li>Team access continues</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;margin:0 0 4px">
      Plans from <strong>NPR {{price}}/month</strong>. Upgrade now and keep working without interruption.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade Now &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Questions about pricing? Reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>.
    </p>`,

  trial_reminder_3d: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your trial ends in 3 days</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your free trial expires on <strong>{{trialEndsAt}}</strong>. After that, you cannot create new BOQs, export tender documents, or upload drawings. Your existing work stays safe.
    </p>
    <div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#1e40af;font-size:14px;font-weight:600;margin:0 0 8px">What you&apos;ll lose without a plan:</p>
      <ul style="color:#1d4ed8;font-size:14px;margin:0;padding-left:20px;line-height:1.8">
        <li>BOQ generation and rate analysis</li>
        <li>PDF drawing takeoff and measurements</li>
        <li>PDF &amp; Excel tender document export</li>
        <li>Team collaboration features</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Your projects, drawings, and data will <strong>remain safe.</strong> You just need to upgrade to keep working.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">View Plans &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Plans start from NPR {{price}}/month for a single user. Annual billing saves you {{annualFreeMonths}} months free.
      Questions? Reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>.
    </p>
    <p style="color:#94a3b8;font-size:13px;margin:12px 0 0">
      P.S. If timing is the issue and you need a few more days, reply and tell us. We can work something out.
    </p>`,

  trial_expired: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your trial has ended</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your Estimate Nepal free trial has ended. Your account is on a limited plan and you&apos;re unable to create new exports, upload drawings, or edit projects.
    </p>
    <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#15803d;font-size:14px;font-weight:600;margin:0 0 4px">Your data is safe</p>
      <p style="color:#166534;font-size:14px;margin:0">
        All your projects, drawings, measurements, and BOQs are preserved. Upgrade now to pick up exactly where you left off.
      </p>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Plans start from <strong>NPR {{price}}/month</strong>. No long-term commitment required.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade Now &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Questions about plans or pricing? Reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>.
      We&apos;re happy to help.
    </p>`,

  reengagement_7: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your Estimate Nepal projects are still here</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      It has been a week since your trial ended.
    </p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Everything you built is still safe. Your projects, your drawings, your measurements, your BOQs.
      All of it is waiting exactly where you left it.
    </p>
    <p style="color:#334155;font-size:15px;margin:0 0 4px">
      Plans start from <strong>NPR {{price}}/month</strong>. No long-term commitment.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Resume Your Project &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Not sure yet? Reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>
      and let us talk. We have helped other contractors find a plan that fits their budget.
    </p>
    <p style="color:#94a3b8;font-size:13px;margin:12px 0 0">
      P.S. If pricing was the issue, just say so. We may have options.
    </p>`,

  reengagement_14: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Two weeks. Your data is still safe.</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Two weeks since your trial ended.
    </p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your projects, drawings, measurements, and BOQs are still here. Nothing has been deleted.
      Upgrade at any time and continue exactly where you stopped.
    </p>
    <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#15803d;font-size:14px;font-weight:600;margin:0 0 4px">Your work is safe</p>
      <p style="color:#166534;font-size:14px;margin:0">Upgrade at any time and continue working. Nothing is lost.</p>
    </div>
    <p style="color:#334155;font-size:15px;margin:0 0 4px">Plans from <strong>NPR {{price}}/month</strong>. No long-term commitment.</p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Continue Where You Left Off &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      If there is a reason you have not come back that you have not told us, reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>.
      We read every message.
    </p>`,

  reengagement_21: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Last chance to keep your data</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your trial ended 3 weeks ago. We will be removing inactive trial data on <strong>{{deletionDate}}</strong>.
      Upgrade before that date to keep your projects, drawings, and measurements permanently.
    </p>
    <div style="background:#fef9f0;border:1px solid #fde68a;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#92400e;font-size:14px;font-weight:600;margin:0 0 4px">Data removal scheduled: {{deletionDate}}</p>
      <p style="color:#78350f;font-size:14px;margin:0">Upgrade before that date to preserve all your work permanently.</p>
    </div>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade and Keep My Data &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Your account will remain active. Only project data is removed. Questions? Write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>.
    </p>`,

  data_warning: `
    <h2 style="color:#dc2626;font-size:22px;font-weight:700;margin:0 0 8px">Your data will be deleted on {{deletionDate}}</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      This is your final notice. Your Estimate Nepal trial data, including all projects, drawings, measurements, and BOQs,
      will be permanently deleted on <strong>{{deletionDate}}</strong>.
    </p>
    <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#991b1b;font-size:14px;font-weight:600;margin:0 0 8px">Scheduled for deletion on {{deletionDate}}:</p>
      <ul style="color:#7f1d1d;font-size:14px;margin:0;padding-left:20px;line-height:1.8">
        <li>All projects and drawings</li>
        <li>All takeoff measurements</li>
        <li>All BOQs and rate analyses</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;font-weight:600;margin:0 0 4px">Upgrade before {{deletionDate}} to save everything permanently.</p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade Now and Save My Data &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Your login account will remain active. Only project data will be removed.
      Need help immediately? Write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>.
    </p>`,

  data_wiped: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your trial data has been removed</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      As notified, your Estimate Nepal trial data has been permanently deleted. Your login account remains active.
    </p>
    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#475569;font-size:14px;line-height:1.7;margin:0">
        If you ever decide to come back, you can upgrade at any time and start fresh with a new project.
        Your account and login credentials are preserved.
      </p>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      If there is anything we could have done better, please write to
      <a href="mailto:hello@estimatenepal.com" style="color:#1d4ed8;text-decoration:none">hello@estimatenepal.com</a>.
      Your feedback helps us build a better product.
    </p>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      You can still log in at <a href="{{baseUrl}}" style="color:#94a3b8">{{baseUrl}}</a>.
    </p>`,

  // C2: churn_reason — {{reasonButtons}} is replaced at send time with dynamically generated button HTML.
  // Required placeholder — do not remove {{reasonButtons}}.
  churn_reason: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">One quick question</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 20px">
      Your trial ended. What stopped you?
    </p>
    <p style="color:#475569;font-size:14px;font-weight:600;margin:0 0 12px">Why didn&apos;t you continue?</p>
    {{reasonButtons}}
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-top:6px">
      <tr><td style="padding:5px 0">
        <a href="{{feedbackUrl}}" style="display:block;background:#ffffff;border:1px dashed #cbd5e1;border-radius:8px;padding:12px 20px;color:#64748b;text-decoration:none;font-size:14px;font-weight:500;text-align:center">
          Something else: tell us in your own words...
        </a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:28px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Changed your mind? Your data is still safe. Reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>
      and we will sort you out.
    </p>`,

  churn_thanks: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Thank you for telling us</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Thank you for taking the time to tell us why you stopped. We read every response. Yours has been noted.
    </p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      If you change your mind, your projects and data are still here.
      You can upgrade at any time and pick up exactly where you left off.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">See What Fits Your Budget &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      If there is more you want to share about what was missing or what could be better, reply to this email or write to
      <a href="mailto:hello@estimatenepal.com" style="color:#94a3b8">hello@estimatenepal.com</a>.
      We read these personally.
    </p>`,

  // C2: nps — {{scoreButtons}} is replaced at send time with 0-10 score button HTML.
  // Required placeholder — do not remove {{scoreButtons}}.
  nps: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">How likely are you to recommend us?</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 20px">
      You&apos;ve been using Estimate Nepal for 10 days. How&apos;s it going? On a scale of 0 to 10, how likely are you to recommend us to a colleague in construction or engineering?
    </p>
    {{scoreButtons}}
    <p style="color:#94a3b8;font-size:13px;margin:28px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      This takes 1 click and helps us improve. Thank you for your time.
    </p>`,

  nps_followup: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">You gave us a {{score}} — we want to understand</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      You rated Estimate Nepal <strong>{{score}} out of 10</strong>. That is not where we want to be for you.
    </p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Can you reply to this email and tell us in one sentence what went wrong or what would make Estimate Nepal a 9 or 10 for you?
      We read every reply personally — this goes directly to the team.
    </p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Or write to us directly:
      <a href="mailto:hello@estimatenepal.com" style="color:#1d4ed8;text-decoration:none">hello@estimatenepal.com</a>
    </p>
    <p style="color:#94a3b8;font-size:13px;margin:28px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Thank you for taking the time to rate us. Your honest feedback is the only way we get better.
    </p>`,
};

// ── Email outer wrapper ────────────────────────────────────────────────────────
// Pure function — no server deps. Safe in client bundles.
// M3: Year is dynamic so it never goes stale.
// H2: Single source of truth for the email frame.
const LOGO_ICON = `<svg width="28" height="28" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" style="display:inline-block;vertical-align:middle"><rect width="40" height="40" rx="10" fill="#1d4ed8"/><rect x="7" y="22" width="6" height="13" rx="1" fill="white" opacity="0.9"/><rect x="17" y="15" width="6" height="20" rx="1" fill="white"/><rect x="27" y="19" width="6" height="16" rx="1" fill="white" opacity="0.85"/><rect x="5" y="36" width="30" height="1.5" rx="0.75" fill="white" opacity="0.45"/></svg>`;

export function wrapEmailHtml(content: string, unsubscribeUrl?: string): string {
  const year = new Date().getFullYear();
  const unsubFooter = unsubscribeUrl
    ? `<p style="text-align:center;font-size:11px;color:#94a3b8;margin:16px 0 0">
        <a href="${unsubscribeUrl}" style="color:#94a3b8;text-decoration:underline">Unsubscribe from marketing emails</a>
       </p>`
    : "";
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Estimate Nepal</title>
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px">
  <tr><td align="center">
    <table width="100%" style="max-width:560px">
      <tr><td style="background:#1d4ed8;border-radius:12px 12px 0 0;padding:24px 32px">
        <table width="100%" cellpadding="0" cellspacing="0"><tr>
          <td style="vertical-align:middle">${LOGO_ICON}</td>
          <td style="vertical-align:middle;padding-left:10px">
            <span style="color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">
              Estimate<span style="color:#93c5fd"> Nepal</span>
            </span>
          </td>
        </tr></table>
      </td></tr>
      <tr><td style="background:#ffffff;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 12px 12px;padding:36px 32px">
        ${content}
        ${unsubFooter}
      </td></tr>
      <tr><td style="padding:24px 0;text-align:center">
        <p style="color:#94a3b8;font-size:12px;margin:0">
          &copy; ${year} Estimate Nepal &middot; estimatenepal.com<br/>
          <span style="color:#cbd5e1">Nepal&apos;s Smart Construction Platform</span>
        </p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;
}
