// Pure constants — no server imports. Safe to use in both server and client components.

export const TEMPLATE_TYPES = [
  "welcome",
  "trial_day7",
  "trial_day12",
  "trial_reminder_3d",
  "trial_expired",
  "reengagement_7",
  "reengagement_14",
  "reengagement_21",
  "data_warning",
  "data_wiped",
  "churn_reason", // C2: survey sent 2-3 days post-expiry
  "nps",          // C2: satisfaction survey sent at day 7 of trial
] as const;

export type TemplateType = (typeof TEMPLATE_TYPES)[number];

export const TEMPLATE_LABELS: Record<TemplateType, string> = {
  welcome:           "Welcome (after email verification)",
  trial_day7:        "Day 7 check-in (7 days into trial)",
  trial_day12:       "Day 12 urgency (2 days left on trial)",
  trial_reminder_3d: "3-day reminder (trial ending soon)",
  trial_expired:     "Trial expired (sent same day)",
  reengagement_7:    "Day 7 post-expiry re-engagement",
  reengagement_14:   "Day 14 post-expiry",
  reengagement_21:   "Day 21 post-expiry (last chance warning)",
  data_warning:      "Day 30 — data deleted in 24 hours",
  data_wiped:        "Day 31 — data has been removed",
  churn_reason:      "Churn survey (2-3 days post-expiry)",
  nps:               "NPS survey (day 7 of trial)",
};

// {{reasonButtons}} and {{scoreButtons}} are special — generated by the cron at send time.
// Do NOT remove these placeholders when editing the churn_reason or nps templates.
export const TEMPLATE_VARS: Record<TemplateType, string[]> = {
  welcome:           ["{{name}}", "{{dashboardUrl}}", "{{trialEndsAt}}"],
  trial_day7:        ["{{name}}", "{{dashboardUrl}}"],
  trial_day12:       ["{{name}}", "{{upgradeUrl}}", "{{trialEndsAt}}"],
  trial_reminder_3d: ["{{name}}", "{{trialEndsAt}}", "{{upgradeUrl}}"],
  trial_expired:     ["{{name}}", "{{upgradeUrl}}"],
  reengagement_7:    ["{{name}}", "{{upgradeUrl}}"],
  reengagement_14:   ["{{name}}", "{{upgradeUrl}}"],
  reengagement_21:   ["{{name}}", "{{upgradeUrl}}"],
  data_warning:      ["{{name}}", "{{upgradeUrl}}"],
  data_wiped:        ["{{name}}", "{{baseUrl}}"],
  churn_reason:      ["{{name}}", "{{reasonButtons}}", "{{feedbackUrl}}"],
  nps:               ["{{name}}", "{{scoreButtons}}"],
};

export const DEFAULT_SUBJECTS: Record<TemplateType, string> = {
  welcome:           "Welcome to Estimate Nepal — here's how to get started",
  trial_day7:        "How's your Estimate Nepal trial going?",
  trial_day12:       "2 days left on your Estimate Nepal trial",
  trial_reminder_3d: "Your Estimate Nepal trial ends in 3 days",
  trial_expired:     "Your Estimate Nepal trial has ended — upgrade to continue",
  reengagement_7:    "We miss you — your Estimate Nepal data is still safe",
  reengagement_14:   "Your data is still waiting — come back to Estimate Nepal",
  reengagement_21:   "Last chance — your Estimate Nepal data will be removed in 9 days",
  data_warning:      "Your Estimate Nepal data will be deleted in 24 hours",
  data_wiped:        "Your Estimate Nepal trial data has been removed",
  churn_reason:      "One quick question about your trial",
  nps:               "Quick question — how's Estimate Nepal working for you?",
};

export const DEFAULT_BODIES: Record<TemplateType, string> = {
  welcome: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Welcome to Estimate Nepal!</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 8px">
      Your email is verified and your 14-day free trial has started.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:0 0 20px">
      <tr><td style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:12px 16px">
        <p style="color:#1e40af;font-size:14px;font-weight:600;margin:0">Trial expires: {{trialEndsAt}}</p>
      </td></tr>
    </table>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 20px">Here&apos;s how to get the most out of it:</p>
    <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px">
      <tr><td style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:16px 20px">
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr><td style="padding:8px 0;border-bottom:1px solid #dbeafe">
            <span style="color:#1d4ed8;font-weight:700;font-size:15px">1.</span>
            <span style="color:#1e40af;font-size:14px;padding-left:8px">Create your first project</span>
          </td></tr>
          <tr><td style="padding:8px 0;border-bottom:1px solid #dbeafe">
            <span style="color:#1d4ed8;font-weight:700;font-size:15px">2.</span>
            <span style="color:#1e40af;font-size:14px;padding-left:8px">Upload a drawing and set the scale</span>
          </td></tr>
          <tr><td style="padding:8px 0">
            <span style="color:#1d4ed8;font-weight:700;font-size:15px">3.</span>
            <span style="color:#1e40af;font-size:14px;padding-left:8px">Measure quantities and export your BOQ</span>
          </td></tr>
        </table>
      </td></tr>
    </table>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Need help getting started? Just reply to this email — we respond within a few hours.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{dashboardUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Go to Dashboard &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      You have <strong>14 days</strong> to explore everything for free. No credit card required.
    </p>`,

  trial_day7: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">How&apos;s your first week going?</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      You&apos;re 7 days into your Estimate Nepal trial — great time to check in. Have you had a chance to explore everything yet?
    </p>
    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#475569;font-size:14px;font-weight:600;margin:0 0 10px">Quick wins to try before your trial ends:</p>
      <ul style="color:#475569;font-size:14px;margin:0;padding-left:20px;line-height:2">
        <li>Upload a drawing and run a takeoff measurement</li>
        <li>Generate a BOQ from your takeoff data</li>
        <li>Export a PDF tender document</li>
        <li>Invite a team member to collaborate</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Reply to this email if you need help getting set up — we respond within a few hours.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{dashboardUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Continue in Dashboard &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      You have 7 days remaining on your free trial.
    </p>`,

  trial_day12: `
    <h2 style="color:#dc2626;font-size:22px;font-weight:700;margin:0 0 8px">2 days left on your trial</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your Estimate Nepal trial expires on <strong>{{trialEndsAt}}</strong>. After that, you won&apos;t be able to create new exports, upload drawings, or edit projects.
    </p>
    <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#991b1b;font-size:14px;font-weight:600;margin:0 0 8px">Don&apos;t lose your work:</p>
      <ul style="color:#7f1d1d;font-size:14px;margin:0;padding-left:20px;line-height:1.8">
        <li>All drawings and measurements preserved</li>
        <li>BOQs and rate analyses kept</li>
        <li>Project history maintained</li>
        <li>Team access continues</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;margin:0 0 4px">
      Plans from <strong>NPR {{price}}/month</strong>. Upgrade now and keep working without interruption.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade Now — Keep Access &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Questions about pricing? Reply to this email — we&apos;re happy to help find the right plan.
    </p>`,

  trial_reminder_3d: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your trial ends in 3 days</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your Estimate Nepal free trial expires on <strong>{{trialEndsAt}}</strong>. After that, you&apos;ll lose access to creating new exports, uploading drawings, and editing projects.
    </p>
    <div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#1e40af;font-size:14px;font-weight:600;margin:0 0 8px">What you&apos;ll lose without a plan:</p>
      <ul style="color:#1d4ed8;font-size:14px;margin:0;padding-left:20px;line-height:1.8">
        <li>BOQ generation and rate analysis</li>
        <li>PDF drawing takeoff and measurements</li>
        <li>PDF &amp; Excel tender document export</li>
        <li>Team collaboration features</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Your projects, drawings, and data will <strong>remain safe</strong> — you just need to upgrade to keep working.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">View Plans &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Plans start from NPR {{price}}/month for a single user. Annual billing saves you {{annualFreeMonths}} months free.
    </p>`,

  trial_expired: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your trial has ended</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your Estimate Nepal free trial has ended. Your account is on a limited plan and you&apos;re unable to create new exports, upload drawings, or edit projects.
    </p>
    <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#15803d;font-size:14px;font-weight:600;margin:0 0 4px">Your data is safe</p>
      <p style="color:#166534;font-size:14px;margin:0">
        All your projects, drawings, measurements, and BOQs are preserved. Upgrade now to pick up exactly where you left off.
      </p>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      Plans start from <strong>NPR {{price}}/month</strong> — no long-term commitment required.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade Now &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Need help choosing a plan? Reply to this email or WhatsApp us — we&apos;re happy to help.
    </p>`,

  reengagement_7: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">We miss you at Estimate Nepal</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your trial ended a week ago. Your projects and all your work are still safe — you just need to upgrade to get back in.
    </p>
    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#475569;font-size:14px;line-height:1.7;margin:0">
        Estimate Nepal helps construction professionals generate accurate BOQs in a fraction of the time —
        with PDF takeoff measurements, rate analysis, and one-click tender document export.
      </p>
    </div>
    <p style="color:#334155;font-size:15px;margin:0 0 4px">
      Plans start from <strong>NPR {{price}}/month</strong>. Upgrade now and pick up exactly where you left off.
    </p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade Now &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Questions? Reply to this email and we&apos;ll help you find the right plan.
    </p>`,

  reengagement_14: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your data is still waiting for you</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      It&apos;s been two weeks since your trial ended. Everything you built — your projects, drawings, measurements, and BOQs — is still intact and ready when you are.
    </p>
    <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#15803d;font-size:14px;font-weight:600;margin:0 0 4px">Your work is safe</p>
      <p style="color:#166534;font-size:14px;margin:0">Upgrade at any time and continue working — nothing is lost.</p>
    </div>
    <p style="color:#334155;font-size:15px;margin:0 0 4px">Plans from <strong>NPR {{price}}/month</strong>. No long-term commitment.</p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Come Back &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Need help or have concerns about pricing? Reply to this email — we&apos;re happy to talk.
    </p>`,

  reengagement_21: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Last chance to keep your data</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      Your trial ended 3 weeks ago. We&apos;ll be removing inactive trial data in <strong>9 days</strong> —
      upgrade now to keep your projects, drawings, and measurements permanently.
    </p>
    <div style="background:#fef9f0;border:1px solid #fde68a;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#92400e;font-size:14px;font-weight:600;margin:0 0 4px">Data removal in 9 days</p>
      <p style="color:#78350f;font-size:14px;margin:0">Upgrade before day 30 to preserve all your work permanently.</p>
    </div>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade and Keep My Data &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Your account will remain active — only project data is removed. Reply to this email if you have questions.
    </p>`,

  data_warning: `
    <h2 style="color:#dc2626;font-size:22px;font-weight:700;margin:0 0 8px">Your data will be deleted in 24 hours</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      This is your final notice. Your Estimate Nepal trial data — including all projects, drawings, measurements, and BOQs —
      will be permanently deleted in <strong>24 hours</strong>.
    </p>
    <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#991b1b;font-size:14px;font-weight:600;margin:0 0 8px">Will be deleted tomorrow:</p>
      <ul style="color:#7f1d1d;font-size:14px;margin:0;padding-left:20px;line-height:1.8">
        <li>All projects and drawings</li>
        <li>All takeoff measurements</li>
        <li>All BOQs and rate analyses</li>
      </ul>
    </div>
    <p style="color:#334155;font-size:15px;font-weight:600;margin:0 0 4px">Upgrade now to save everything permanently.</p>
    <table cellpadding="0" cellspacing="0" style="margin:28px 0">
      <tr><td style="background:#1d4ed8;border-radius:8px">
        <a href="{{upgradeUrl}}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px">Upgrade Now — Save My Data &rarr;</a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Your login account will remain active. Only project data will be removed.
      Reply to this email immediately if you need help.
    </p>`,

  // L1: Use {{baseUrl}} placeholder instead of hardcoded estimatenepal.com
  data_wiped: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">Your trial data has been removed</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 16px">
      As notified, your Estimate Nepal trial data has been permanently deleted. Your login account remains active.
    </p>
    <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px 20px;margin:0 0 20px">
      <p style="color:#475569;font-size:14px;line-height:1.7;margin:0">
        If you ever decide to come back, you can upgrade at any time and start fresh with a new project.
        Your account and login credentials are preserved.
      </p>
    </div>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 4px">
      We&apos;re sorry to see you go. If there&apos;s anything we could have done better,
      please reply to this email — your feedback helps us improve.
    </p>
    <p style="color:#94a3b8;font-size:13px;margin:24px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      You can still log in at <a href="{{baseUrl}}" style="color:#94a3b8">{{baseUrl}}</a>.
    </p>`,

  // C2: churn_reason — {{reasonButtons}} is replaced at send time with dynamically generated button HTML.
  // Required placeholder — do not remove {{reasonButtons}}.
  churn_reason: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">One quick question</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 20px">
      Your Estimate Nepal trial has ended. We&apos;d love to know what stopped you — it takes one click and helps us build a better product for Nepal&apos;s construction industry.
    </p>
    <p style="color:#475569;font-size:14px;font-weight:600;margin:0 0 12px">Why didn&apos;t you continue?</p>
    {{reasonButtons}}
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-top:6px">
      <tr><td style="padding:5px 0">
        <a href="{{feedbackUrl}}" style="display:block;background:#ffffff;border:1px dashed #cbd5e1;border-radius:8px;padding:12px 20px;color:#64748b;text-decoration:none;font-size:14px;font-weight:500;text-align:center">
          Something else — tell us in your own words&hellip;
        </a>
      </td></tr>
    </table>
    <p style="color:#94a3b8;font-size:13px;margin:28px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      Changed your mind? Your data is still safe — reply to this email and we&apos;ll help you get back in.
    </p>`,

  // C2: nps — {{scoreButtons}} is replaced at send time with 0–10 score button HTML.
  // Required placeholder — do not remove {{scoreButtons}}.
  nps: `
    <h2 style="color:#0f172a;font-size:22px;font-weight:700;margin:0 0 8px">How likely are you to recommend us?</h2>
    <p style="color:#64748b;font-size:15px;margin:0 0 20px">Hi {{name}},</p>
    <p style="color:#334155;font-size:15px;line-height:1.6;margin:0 0 20px">
      You&apos;ve been using Estimate Nepal for a week — how&apos;s it going? On a scale of 0–10, how likely are you to recommend us to a colleague in construction or engineering?
    </p>
    {{scoreButtons}}
    <p style="color:#94a3b8;font-size:13px;margin:28px 0 0;padding-top:24px;border-top:1px solid #f1f5f9">
      This takes 1 click and helps us improve. Thank you for your time.
    </p>`,
};

// ── Email outer wrapper ────────────────────────────────────────────────────────
// Pure function — no server deps. Safe in client bundles.
// M3: Year is dynamic so it never goes stale.
// H2: This is the single source of truth. lib/email.ts imports this instead of duplicating.
const LOGO_ICON = `<svg width="28" height="28" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" style="display:inline-block;vertical-align:middle"><rect width="40" height="40" rx="10" fill="#1d4ed8"/><rect x="7" y="22" width="6" height="13" rx="1" fill="white" opacity="0.9"/><rect x="17" y="15" width="6" height="20" rx="1" fill="white"/><rect x="27" y="19" width="6" height="16" rx="1" fill="white" opacity="0.85"/><rect x="5" y="36" width="30" height="1.5" rx="0.75" fill="white" opacity="0.45"/></svg>`;

export function wrapEmailHtml(content: string, unsubscribeUrl?: string): string {
  const year = new Date().getFullYear();
  const unsubFooter = unsubscribeUrl
    ? `<p style="text-align:center;font-size:11px;color:#94a3b8;margin:16px 0 0">
        <a href="${unsubscribeUrl}" style="color:#94a3b8;text-decoration:underline">Unsubscribe from marketing emails</a>
       </p>`
    : "";
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Estimate Nepal</title>
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px">
  <tr><td align="center">
    <table width="100%" style="max-width:560px">
      <tr><td style="background:#1d4ed8;border-radius:12px 12px 0 0;padding:24px 32px">
        <table width="100%" cellpadding="0" cellspacing="0"><tr>
          <td style="vertical-align:middle">${LOGO_ICON}</td>
          <td style="vertical-align:middle;padding-left:10px">
            <span style="color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">
              Estimate<span style="color:#93c5fd"> Nepal</span>
            </span>
          </td>
        </tr></table>
      </td></tr>
      <tr><td style="background:#ffffff;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 12px 12px;padding:36px 32px">
        ${content}
        ${unsubFooter}
      </td></tr>
      <tr><td style="padding:24px 0;text-align:center">
        <p style="color:#94a3b8;font-size:12px;margin:0">
          &copy; ${year} Estimate Nepal &mdash; estimatenepal.com<br/>
          <span style="color:#cbd5e1">Nepal&apos;s Smart Construction Platform</span>
        </p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;
}
